#!/bin/bash     

my_dir="$(dirname "$0")"

source $my_dir/janus_header

function usage {
    echo "Janus DSL Interpreter"
    echo "Usage: "
    echo "./jdsl_run <executable> [executable_args ...]"
}

if [ $# -lt "1" ]
then 
    usage
    exit
fi

binfile=$1
shift

hintfile="$binfile.jrs"

if [ -f $binfile ];
then
   echo "Found executable $binfile"
else
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

$JANUSBIN/analyze -c $binfile

# To run:
$TOOLDIR/bin64/drrun -ops "-opt_cleancall 0 -thread_private" -c $JANUSLIB/libjdsl.so @$hintfile @1 @0 -- $binfile $*

# To run on only one CPU:
#taskset --cpu-list 1 $TOOLDIR/bin64/drrun -ops "-opt_cleancall 0 -thread_private" -c $JANUSLIB/libjdsl.so @$hintfile @1 @0 -- $binfile $*

# For debugging messages use:
#$TOOLDIR/bin64/drrun -debug -ops "-checklevel 0 -opt_cleancall 0 -thread_private" -c $JANUSLIB/libjdsl.so @$hintfile @1 @0 -- $binfile $*

# For debugging use:
#gdb --args $TOOLDIR/bin64/drrun -debug -ops "-checklevel 0 -opt_cleancall 0 -thread_private" -c $JANUSLIB/libjdsl.so @$hintfile @1 @0 -- $binfile $*

# Run without client
#$TOOLDIR/bin64/drrun -ops "-opt_cleancall 0 -thread_private" -- $binfile $*
